In [14]:
from src.feature_selection import *

X_raw.head()

  Final: 163752 rows, 49 features
[1.13] Normalizing (MinMaxScaler)...
[1.13] Feature selection...
[1.14] Normalizing (MinMaxScaler)...
[1.13] Feature selection (strong reduction, train-only)...
  Removed module dummies: 7
  Removed high-missing: 0
  Removed low-variance: 0
  Removed highly correlated: 6
  Final selected features: 30
  Train: (131001, 30)   Test: (32751, 30)

,num_of_prev_attempts,studied_credits,disability_bin,gender_bin,imd_band_ord,highest_education_ord,age_band_ord,total_clicks,total_vle_interactions,unique_active_days,...,mod_BBB,mod_CCC,mod_DDD,mod_EEE,mod_FFF,mod_GGG,pres_2013B,pres_2013J,pres_2014B,pres_2014J
0,0,240,0,1,10.0,3,2,934.0,196.0,40.0,...,0,0,0,0,0,0,0,1,0,0
1,0,240,0,1,10.0,3,2,934.0,196.0,40.0,...,0,0,0,0,0,0,0,1,0,0
2,0,240,0,1,10.0,3,2,934.0,196.0,40.0,...,0,0,0,0,0,0,0,1,0,0
3,0,240,0,1,10.0,3,2,934.0,196.0,40.0,...,0,0,0,0,0,0,0,1,0,0
4,0,240,0,1,10.0,3,2,934.0,196.0,40.0,...,0,0,0,0,0,0,0,1,0,0

In [15]:
X_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163752 entries, 0 to 163751
Data columns (total 49 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   num_of_prev_attempts         163752 non-null  int64
 1   studied_credits              163752 non-null  int64
 2   disability_bin               163752 non-null  int64
 3   gender_bin                   163752 non-null  int64
 4   imd_band_ord                 163752 non-null  float64
 5   highest_education_ord        163752 non-null  int8
 6   age_band_ord                 163752 non-null  int8
 7   total_clicks                 163752 non-null  float64
 8   total_vle_interactions       163752 non-null  float64
 9   unique_active_days           163752 non-null  float64
 10  activity_span_days           163752 non-null  float64
 11  avg_clicks_per_day           163752 non-null  float64
 12  clicks_before_deadline       163752 non-null  float64
 13  active_days_before_deadline  163752 non-null  float64
 14  assessment_number            163752 non-null  int64
 15  prior_mean_score             163752 non-null  float64
 16  prior_min_score              163752 non-null  float64
 17  prior_max_score              163752 non-null  float64
 18  prior_last_score             163752 non-null  float64
 19  prior_std_score              163752 non-null  float64
 20  clicks_x_days_before         163752 non-null  float64
 21  active_ratio                 163752 non-null  float64
 22  click_intensity              163752 non-null  float64
 23  late_x_clicks                163752 non-null  float64
 24  edu_x_clicks                 163752 non-null  float64
 25  prior_score_x_clicks         163752 non-null  float64
 26  total_clicks_log             163752 non-null  float64
 27  total_vle_interactions_log   163752 non-null  float64
 28  clicks_before_deadline_log   163752 non-null  float64
 29  click_intensity_log          163752 non-null  float64
 30  clicks_x_days_before_log     163752 non-null  float64
 31  days_before_deadline         163752 non-null  float64
 32  is_late                      163752 non-null  int64
 33  abs_days_from_deadline       163752 non-null  float64
 34  weight                       163752 non-null  float64
 35  atype_CMA                    163752 non-null  int64
 36  atype_Exam                   163752 non-null  int64
 37  atype_TMA                    163752 non-null  int64
 38  mod_AAA                      163752 non-null  int64
 39  mod_BBB                      163752 non-null  int64
 40  mod_CCC                      163752 non-null  int64
 41  mod_DDD                      163752 non-null  int64
 42  mod_EEE                      163752 non-null  int64
 43  mod_FFF                      163752 non-null  int64
 44  mod_GGG                      163752 non-null  int64
 45  pres_2013B                   163752 non-null  int64
 46  pres_2013J                   163752 non-null  int64
 47  pres_2014B                   163752 non-null  int64
 48  pres_2014J                   163752 non-null  int64
dtypes: float64(27), int64(20), int8(2)
memory usage: 59.0 MB

In [16]:
X_raw.describe()

,num_of_prev_attempts,studied_credits,disability_bin,gender_bin,imd_band_ord,highest_education_ord,age_band_ord,total_clicks,total_vle_interactions,unique_active_days,...,mod_BBB,mod_CCC,mod_DDD,mod_EEE,mod_FFF,mod_GGG,pres_2013B,pres_2013J,pres_2014B,pres_2014J
count,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,...,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000,163752.000000
mean,0.144566,76.755490,0.087040,0.539633,5.229176,1.800198,0.320595,1967.690056,513.915012,84.030577,...,0.247362,0.108762,0.177268,0.045612,0.315269,0.087633,0.194367,0.282329,0.223893,0.299410
std,0.444821,37.351476,0.281895,0.498428,3.023447,0.747712,0.480847,2029.101046,417.158468,54.306246,...,0.431480,0.311341,0.381897,0.208642,0.464625,0.282761,0.395714,0.450134,0.416853,0.458001
min,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,60.000000,0.000000,0.000000,3.000000,1.000000,0.000000,585.000000,203.000000,41.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,60.000000,0.000000,1.000000,5.000000,2.000000,0.000000,1290.000000,394.000000,74.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,90.000000,0.000000,1.000000,8.000000,2.000000,1.000000,2696.000000,711.000000,117.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,6.000000,630.000000,1.000000,1.000000,10.000000,4.000000,2.000000,24139.000000,3078.000000,286.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [33]:
from sklearn.feature_selection import SelectKBest, f_regression
# Select top 20 features
selector = SelectKBest(score_func=f_regression, k=35)
X_selected = selector.fit_transform(X_raw, y)
selected_features = X_raw.columns[selector.get_support()]
print(selector.get_params())
print("Selected Features:")
print(selected_features)

{'k': 35, 'score_func': <function f_regression at 0x000001D193D30360>}
Selected Features:
Index(['num_of_prev_attempts', 'imd_band_ord', 'highest_education_ord',
       'age_band_ord', 'total_clicks', 'total_vle_interactions',
       'unique_active_days', 'activity_span_days', 'avg_clicks_per_day',
       'clicks_before_deadline', 'active_days_before_deadline',
       'assessment_number', 'prior_mean_score', 'prior_min_score',
       'prior_max_score', 'prior_last_score', 'prior_std_score',
       'clicks_x_days_before', 'active_ratio', 'click_intensity',
       'edu_x_clicks', 'prior_score_x_clicks', 'total_clicks_log',
       'total_vle_interactions_log', 'clicks_before_deadline_log',
       'click_intensity_log', 'clicks_x_days_before_log',
       'days_before_deadline', 'abs_days_from_deadline', 'weight', 'atype_CMA',
       'atype_Exam', 'atype_TMA', 'mod_DDD', 'mod_FFF'],
      dtype='object')

In [34]:
x_new = X_raw[selected_features]
x_new.head()

,num_of_prev_attempts,imd_band_ord,highest_education_ord,age_band_ord,total_clicks,total_vle_interactions,unique_active_days,activity_span_days,avg_clicks_per_day,clicks_before_deadline,...,click_intensity_log,clicks_x_days_before_log,days_before_deadline,abs_days_from_deadline,weight,atype_CMA,atype_Exam,atype_TMA,mod_DDD,mod_FFF
0,0,10.0,3,2,934.0,196.0,40.0,258.0,23.35,401.0,...,3.934274,5.996452,1.0,1.0,10.0,0,0,1,0,0
1,0,10.0,3,2,934.0,196.0,40.0,258.0,23.35,529.0,...,3.414077,6.272877,1.0,1.0,20.0,0,0,1,0,0
2,0,10.0,3,2,934.0,196.0,40.0,258.0,23.35,628.0,...,3.225011,7.136483,2.0,2.0,20.0,0,0,1,0,0
3,0,10.0,3,2,934.0,196.0,40.0,258.0,23.35,713.0,...,3.178054,7.263330,2.0,2.0,20.0,0,0,1,0,0
4,0,10.0,3,2,934.0,196.0,40.0,258.0,23.35,791.0,...,3.189023,7.772332,3.0,3.0,30.0,0,0,1,0,0

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x_new, y, test_size=0.2, random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler


x_scaler = StandardScaler()
X_train_scaled = x_scaler.fit_transform(X_train)
X_test_scaled = x_scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R^2 Score: {r2:.2f}")

Mean Squared Error: 237.04
R^2 Score: 0.31

In [37]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
poly_model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
poly_model.fit(X_train_scaled, y_train)
y_poly_pred = poly_model.predict(X_test_scaled)
mse_poly = mean_squared_error(y_test, y_poly_pred)
r2_poly = r2_score(y_test, y_poly_pred)
print(f"Polynomial Mean Squared Error: {mse_poly:.2f}")
print(f"Polynomial R^2 Score: {r2_poly:.2f}")

Polynomial Mean Squared Error: 203.12
Polynomial R^2 Score: 0.41

In [39]:
model = xgb.XGBRegressor(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    tree_method='hist',
    device='cuda',
    random_state=42
)
model.fit(X_train_scaled, y_train)
y_xgb_pred = model.predict(X_test_scaled)
mse_xgb = mean_squared_error(y_test, y_xgb_pred)
r2_xgb = r2_score(y_test, y_xgb_pred)
print(f"XGBoost Mean Squared Error: {mse_xgb:.2f}")
print(f"XGBoost R^2 Score: {r2_xgb:.2f}")

XGBoost Mean Squared Error: 190.55
XGBoost R^2 Score: 0.45

In [40]:
from sklearn.cross_decomposition import PLSRegression
pls = PLSRegression(n_components=10)
pls.fit(X_train_scaled, y_train)
y_pls_pred = pls.predict(X_test_scaled)
mse_pls = mean_squared_error(y_test, y_pls_pred)
r2_pls = r2_score(y_test, y_pls_pred)
print(f"PLS Mean Squared Error: {mse_pls:.2f}")
print(f"PLS R^2 Score: {r2_pls:.2f}")

PLS Mean Squared Error: 238.42
PLS R^2 Score: 0.31

In [42]:
'''from sklearn.model_selection import RandomizedSearchCV
param_dist = {
    'n_estimators': [100, 300, 500, 700, 1000],
    'max_depth': [4, 6, 8,10, 12],
    'learning_rate': [0.01, 0.05, 0.1]
}
xgb_model = xgb.XGBRegressor(tree_method='hist', device='cuda', random_state=42)
random_search = RandomizedSearchCV(xgb_model, param_distributions=param_dist, n_iter=20, cv=3, verbose=2, random_state=42)
random_search.fit(X_train_scaled, y_train)
print(random_search.best_params_)
best_xgb = random_search.best_estimator_'''
model = xgb.XGBRegressor(
    n_estimators=700,
    max_depth=6,
    learning_rate=0.05,
    tree_method='hist',
    device='cuda',
    random_state=42
)
model.fit(X_train_scaled, y_train)
y_best_xgb_pred = model.predict(X_test_scaled)
mse_best_xgb = mean_squared_error(y_test, y_best_xgb_pred)
r2_best_xgb = r2_score(y_test, y_best_xgb_pred)
print(f"Best XGBoost Mean Squared Error: {mse_best_xgb:.2f}")
print(f"Best XGBoost R^2 Score: {r2_best_xgb:.2f}")

Best XGBoost Mean Squared Error: 189.98
Best XGBoost R^2 Score: 0.45